channels:
- conda-forge
dependencies:
# Jupyter
- jupyterlab=3
- nodejs=12
- nbconvert=6
- widgetsnbextension=3.5
# Python Kernel
- ipykernel=5.1
- ipywidgets=7.6
# - ipyleaflet=0.12
- ipympl=1.0.1
#- altair=3.1
#- bqplot=0.12
#- dask=2.1
- lmfit
- matplotlib=3.1
- pandas=1
- python=3.7
#- scikit-image=0.15
#- scikit-learn=0.21
#- seaborn=0.11
#- tensorflow=1.13
- sympy=1.4
- pyyaml
- traittypes==0.2.1
- invoke=1.2
# C++ Kernel
#- xeus-cling
#- xtensor
#- xtensor-blas
#- xwidgets
#- xleaflet
# R Kernel
#- r-ggplot2
#- r-irkernel
