#!/bin/bash
set -e

SETTINGS_DIR=$(python -c "import sys; print(sys.prefix)")/share/jupyter/lab/settings
mkdir -p "${SETTINGS_DIR}"
cat > "${SETTINGS_DIR}/overrides.json" << 'EOF'
{
  "@jupyterlab/translation-extension:plugin": {
    "locale": "fr_FR"
  }
}
EOF
